In [21]:
import pandas as pd
from sqlalchemy import create_engine

In [22]:
read_2015= pd.read_csv('datasets_894_813759_2015.csv')
read_2015

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Switzerland,Western Europe,1,7.587,1.39651,0.94143,0.66557,0.41978,0.29678
1,Iceland,Western Europe,2,7.561,1.30232,0.94784,0.62877,0.14145,0.43630
2,Denmark,Western Europe,3,7.527,1.32548,0.87464,0.64938,0.48357,0.34139
3,Norway,Western Europe,4,7.522,1.45900,0.88521,0.66973,0.36503,0.34699
4,Canada,North America,5,7.427,1.32629,0.90563,0.63297,0.32957,0.45811
...,...,...,...,...,...,...,...,...,...
153,Rwanda,Sub-Saharan Africa,154,3.465,0.22208,0.42864,0.59201,0.55191,0.22628
154,Benin,Sub-Saharan Africa,155,3.340,0.28665,0.31910,0.48450,0.08010,0.18260
155,Syria,Middle East and Northern Africa,156,3.006,0.66320,0.72193,0.15684,0.18906,0.47179
156,Burundi,Sub-Saharan Africa,157,2.905,0.01530,0.22396,0.11850,0.10062,0.19727
157,Togo,Sub-Saharan Africa,158,2.839,0.20868,0.28443,0.36453,0.10731,0.16681

In [23]:
country_region= read_2015.drop(['Happiness Rank', 'Happiness Score',  'Economy (GDP per Capita)',  'Health (Life Expectancy)','Freedom', 'Trust (Government Corruption)', 'Generosity', ], axis=1)
# country_region

In [24]:
happiness_2016= pd.read_csv('datasets_894_813759_2016.csv')
happiness_2016

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Denmark,Western Europe,1,7.526,1.44178,0.79504,0.57941,0.44453,0.36171
1,Switzerland,Western Europe,2,7.509,1.52733,0.86303,0.58557,0.41203,0.28083
2,Iceland,Western Europe,3,7.501,1.42666,0.86733,0.56624,0.14975,0.47678
3,Norway,Western Europe,4,7.498,1.57744,0.79579,0.59609,0.35776,0.37895
4,Finland,Western Europe,5,7.413,1.40598,0.81091,0.57104,0.41004,0.25492
...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,0.39499,0.21028,0.39747,0.06681,0.20180
153,Afghanistan,Southern Asia,154,3.360,0.38227,0.17344,0.16430,0.07112,0.31268
154,Togo,Sub-Saharan Africa,155,3.303,0.28123,0.24811,0.34678,0.11587,0.17517
155,Syria,Middle East and Northern Africa,156,3.069,0.74719,0.62994,0.06912,0.17233,0.48397
156,Burundi,Sub-Saharan Africa,157,2.905,0.06831,0.15747,0.04320,0.09419,0.20290

In [25]:
read_2017= pd.read_csv('datasets_894_813759_2017.csv')
happiness_2017 = read_2017.drop(['Whisker.high', 'Whisker.low'],axis=1)

In [26]:
merged_inner_2017 = pd.merge(left=country_region, right=happiness_2017, left_on='Country', right_on='Country')
merged_inner_2017

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Switzerland,Western Europe,4,7.494,1.564980,0.858131,0.620071,0.367007,0.290549
1,Iceland,Western Europe,3,7.504,1.480633,0.833552,0.627163,0.153527,0.475540
2,Denmark,Western Europe,2,7.522,1.482383,0.792566,0.626007,0.400770,0.355280
3,Norway,Western Europe,1,7.537,1.616463,0.796667,0.635423,0.315964,0.362012
4,Canada,North America,7,7.316,1.479204,0.834558,0.611101,0.287372,0.435540
...,...,...,...,...,...,...,...,...,...
144,Rwanda,Sub-Saharan Africa,151,3.471,0.368746,0.326425,0.581844,0.455220,0.252756
145,Benin,Sub-Saharan Africa,143,3.657,0.431085,0.209930,0.425963,0.060929,0.207948
146,Syria,Middle East and Northern Africa,152,3.462,0.777153,0.500533,0.081539,0.151347,0.493664
147,Burundi,Sub-Saharan Africa,154,2.905,0.091623,0.151611,0.059901,0.084148,0.204435
148,Togo,Sub-Saharan Africa,150,3.495,0.305445,0.247106,0.380426,0.095665,0.196896

In [27]:
happiness_2018= pd.read_csv('datasets_894_813759_2018.csv')

In [34]:
merged_inner_2018 = pd.merge(left=country_region, right=happiness_2018, left_on='Country', right_on='Country or region')

In [33]:
data_2018= merged_inner_2018.drop(['Country or region'], axis=1)
data_2018

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Healthy (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Switzerland,Western Europe,5,7.487,1.420,0.927,0.660,0.357,0.256
1,Iceland,Western Europe,4,7.495,1.343,0.914,0.677,0.138,0.353
2,Denmark,Western Europe,3,7.555,1.351,0.868,0.683,0.408,0.284
3,Norway,Western Europe,2,7.594,1.456,0.861,0.686,0.340,0.286
4,Canada,North America,7,7.328,1.330,0.896,0.653,0.291,0.321
...,...,...,...,...,...,...,...,...,...
145,Rwanda,Sub-Saharan Africa,151,3.408,0.332,0.400,0.636,0.444,0.200
146,Benin,Sub-Saharan Africa,136,4.141,0.378,0.240,0.440,0.067,0.163
147,Syria,Middle East and Northern Africa,150,3.462,0.689,0.539,0.088,0.144,0.376
148,Burundi,Sub-Saharan Africa,156,2.905,0.091,0.145,0.065,0.076,0.149
149,Togo,Sub-Saharan Africa,139,3.999,0.259,0.253,0.434,0.101,0.158

In [29]:
happiness_2019= pd.read_csv('datasets_894_813759_2019.csv')

In [35]:
merged_inner_2019 = pd.merge(left=country_region, right=happiness_2019, left_on='Country', right_on='Country or region')

In [32]:
data_2019= merged_inner_2019.drop(['Country or region'], axis=1)
data_2019

,Country,Region,Happiness Rank,Happiness Score,Economy (GDP per Capita),Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity
0,Switzerland,Western Europe,6,7.480,1.452,1.052,0.572,0.343,0.263
1,Iceland,Western Europe,4,7.494,1.380,1.026,0.591,0.118,0.354
2,Denmark,Western Europe,2,7.600,1.383,0.996,0.592,0.410,0.252
3,Norway,Western Europe,3,7.554,1.488,1.028,0.603,0.341,0.271
4,Canada,North America,9,7.278,1.365,1.039,0.584,0.308,0.285
...,...,...,...,...,...,...,...,...,...
144,Rwanda,Sub-Saharan Africa,152,3.334,0.359,0.614,0.555,0.411,0.217
145,Benin,Sub-Saharan Africa,102,4.883,0.393,0.397,0.349,0.082,0.175
146,Syria,Middle East and Northern Africa,149,3.462,0.619,0.440,0.013,0.141,0.331
147,Burundi,Sub-Saharan Africa,145,3.775,0.046,0.380,0.220,0.180,0.176
148,Togo,Sub-Saharan Africa,139,4.085,0.275,0.410,0.293,0.085,0.177